# Generated by Django 3.1.3 on 2020-11-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ManyToManyField(blank=True, related_name='productos', to='app_productos.Producto'),
        ),
    ]
