# Generated by Django 3.1.3 on 2020-11-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0002_auto_20201129_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_lente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.CharField(max_length=64)),
                ('lado', models.CharField(max_length=64)),
                ('armazon', models.CharField(max_length=64)),
            ],
        ),
    ]
