# Generated by Django 3.1.3 on 2020-12-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0005_auto_20201201_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_lente',
            name='armazon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipo_lente',
            name='cerca',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipo_lente',
            name='derecha',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipo_lente',
            name='izquierda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipo_lente',
            name='lejos',
            field=models.BooleanField(default=False),
        ),
    ]
